### ISSUE TITLE
Update the order of account list on the "Send to" screen to match the order from the dropdown list

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#12960]
**User Story**
This issue is a result of this bug report: #12885 where the order of accounts listed doesn't match the user expectation. 

**Steps to reproduce the bug**
Create at least 10 accounts with each respective name being "Account 1", "Account 2", "Account 3", ... , "Account 10"
Click "Send"
Click "Transfer between my accounts"
See mis-ordered accounts (e.g. "Account 10" shows up before "Account 2").

**Task**
Update the order of the account list on the "Send to" screen (1st screenshot) to match the same order from the dropdown list (2nd screenshot)

Send to screen:
<img width="351" alt="Screen Shot 2021-12-02 at 19 38 25" src="https://user-images.githubusercontent.com/34968356/144514664-c9e61467-6c57-4a27-8bb1-f2a7a38b4b49.png">

Dropdown list:
<img width="355" alt="Screen Shot 2021-12-02 at 19 38 04" src="https://user-images.githubusercontent.com/34968356/144514741-52002de4-5df4-48cf-969c-b279d31c7cd9.png">

**Acceptance criteria:**
- [ ] Accounts on the "Send to" screen are listed in the same order as the dropdown list
- [ ] Changing account's names doesn't change the order they are shown on the "Send to" screen
- [ ] There are no changes made to the order of accounts on the dropdown list

**Comment by darkwing** [comment]
Closed as fixed.
