### ISSUE TITLE
Increase e2e test coverage 

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#13478]
- [ ] Test Dapp
  - [x] ~Message signing~ https://github.com/MetaMask/metamask-extension/pull/13507
  - [ ] web3.js 
  - [x] Encrypt/Decrypt flow https://github.com/MetaMask/metamask-extension/issues/14325 (https://github.com/MetaMask/metamask-extension/pull/16122)
- [ ] Connected Sites
  - [ ]  Switch account
  - [ ] Disconnect - https://github.com/MetaMask/metamask-extension/pull/13350
  - [ ] Manual connect
- [ ] Transactions (Error cases)
  - [x] #16136
  - [ ] Insufficient funds warning
- [ ] Networks 
  - [x] 1559 supported
  - [ ] custom
  - [ ] Optimism
- [x] Swaps (https://github.com/MetaMask/metamask-extension/pull/12806)
- [ ] Transaction Insights (Contract metadata)
- [ ] Incoming transactions https://github.com/MetaMask/metamask-extension/issues/21258
- [ ] Tokens
  - [ ] auto detect https://github.com/MetaMask/metamask-extension/issues/21256
- [x] NFTs 
  - [x] Import
  - [x] send https://github.com/MetaMask/metamask-extension/pull/15481
  - [x] auto detect https://github.com/MetaMask/metamask-extension/issues/21257
  - [x] approvals https://github.com/MetaMask/metamask-extension/pull/15481
- [x] Contacts (Edit, Delete) (https://github.com/metamask/metamask-extension/issues/13500)
- [x] Ens (Resolution) (https://github.com/MetaMask/metamask-extension/issues/17708)
- [x] Phishing detection (Warning list)
  - [x] ~Add coverage~ https://github.com/MetaMask/metamask-extension/pull/13704
  - [x] ~Skip tests due to ganache shutdown issues~ https://github.com/MetaMask/metamask-extension/pull/13878
  - [x] Remove skip flag so tests are run 
- [ ] Deposit Ether (Wyre, Transak, Moonpay)
- [ ] Connect hardware wallet (Ledger, Trezor, Lattice, QR based)
- [x] Update testing libraries
  - [x] ~Selenium Webdriver~ https://github.com/MetaMask/metamask-extension/pull/12922
  - [x]  ~Chromedriver~ https://github.com/MetaMask/metamask-extension/pull/13616
  - [x] Geckodriver https://github.com/MetaMask/metamask-extension/pull/16383
  - [x]  ~Ganache~ (https://github.com/MetaMask/metamask-extension/pull/13282, https://github.com/MetaMask/metamask-extension/pull/13354)
- [x] Framework enhancements
  - [x] ~Mock network requests~ https://github.com/MetaMask/metamask-extension/pull/13640
  - [x] Parallel test runs - https://github.com/MetaMask/metamask-extension/issues/10759
  - [x] Ganache state - already deployed contracts
    - [x] step 1 https://github.com/MetaMask/metamask-extension/issues/14263
    - [x] step 2 https://github.com/MetaMask/test-dapp/issues/160
    - [x] step 3 https://github.com/MetaMask/metamask-extension/issues/14262 https://github.com/MetaMask/metamask-extension/issues/15417
- [ ] Refactor (finish migrating tests to use fixtures) (https://github.com/MetaMask/metamask-extension/issues/11136)
  - [x] step 1 https://github.com/MetaMask/metamask-extension/issues/13674
  - [ ] step 2 https://github.com/MetaMask/metamask-extension/issues/13676
  - [x] step 3 https://github.com/MetaMask/metamask-extension/issues/13677
- [x] Document best practices, refactors & improvements https://github.com/MetaMask/metamask-extension/issues/16376
- [x] Support initializing blockchain state with test data. Option 1: deploy contracts, via scripts, to ganache before starting app. https://github.com/MetaMask/metamask-extension/issues/14263
- [x] MV3 pipeline checks https://github.com/MetaMask/metamask-extension/issues/14326
- [x] Fixture data files https://github.com/MetaMask/metamask-extension/issues/14340 (https://github.com/MetaMask/metamask-extension/pull/16061)

**Comment by danjm** [comment]
Should we also add e2e tests for all the signing methods?

**Comment by gauthierpetetin** [comment]
Hi @chloeYue , are open issues still valid? Or shall this epic be closed?

**Comment by gauthierpetetin** [comment]
Closing as outdated
