### ISSUE TITLE
[Tracking] Improve Optimism UX

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#13545]
Hello team! I've opened a series of small issues to remove some common friction and painpoints when using MetaMask on Optimism. I imagine some of these may be generalizable to other L2s, although I kept them specific and will let you determine whether that's actually the case. 

- [x] https://github.com/MetaMask/metamask-extension/issues/13541
- [x] https://github.com/MetaMask/metamask-extension/issues/13542
- [x] https://github.com/MetaMask/metamask-extension/issues/13543
- [x] https://github.com/MetaMask/metamask-extension/issues/13544
- [ ] https://github.com/MetaMask/metamask-extension/issues/13546

This is a tracking issue for general conversation. If you're tracking this stuff elsewhere, let me know or feel free to close these out. Also, if any of these are particularly well-suited for external PRs, please let us know! ❤️

**Comment by qbzzt** [comment]
I try to go to the block explorer on Optimistic Kovan, Metamask sends me instead to optimism.io:

https://www.optimism.io/tx/0x928e958c157ccb4f573466aef47da0eb1dc00fbdad3e286b102eea6ce0a9cc67
