### ISSUE TITLE
Event tracking for Token Detection V2

### ISSUE THREAD

**Issue by NiranjanaBinoy** [MetaMask/metamask-extension#13951]
Adding event tracking on improved token detection.

https://www.notion.so/896022ba921347be8a7058d0641b6d00?v=224f52511d34479695d770a61b20d914

**Tasks**
- [ ] [Token Autodetection](https://www.notion.so/Token-Autodetection-7735db4678c248d8bd80ef21ef4c1c0b)

- [ ] [Token Added](https://www.notion.so/Token-Added-7c29eb0a7dbe49bea75b9a863b18b039)

- [ ] [Token Not Added](https://www.notion.so/Token-Not-Added-7dfbc0f511494993aff3553e728bb6dd)

**Comment by brad-decker** [comment]
#12829 is the original ticket, providing details, but this ticket has more itemized action items. I am going to close that other one, i've added this ticket to event system epic and added the metrics label. @hilvmason

**Comment by brad-decker** [comment]
@NiranjanaBinoy there's a lot of comments on that old ticket, let me know if you have any questions
