### ISSUE TITLE
Add New Tokens Found page

### ISSUE THREAD

**Issue by NiranjanaBinoy** [MetaMask/metamask-extension#13950]
Add ‘x’ new tokens found page to display detected tokens with the ability to ignore or add token

- [ ] Token address component - #14104 
<img width="269" alt="Screen Shot 2022-03-18 at 4 31 41 PM" src="https://user-images.githubusercontent.com/43930900/159079140-e75d956c-e2e5-4e55-bff5-4bdfc50497a6.png">

- [ ] Token list component - #14157 
<img width="214" alt="Screen Shot 2022-03-18 at 4 32 17 PM" src="https://user-images.githubusercontent.com/43930900/159079222-9cf2864f-fbb5-40b7-b98c-af951b3f881f.png">
<img width="215" alt="Screen Shot 2022-03-18 at 4 32 41 PM" src="https://user-images.githubusercontent.com/43930900/159079274-1721fb4c-57b9-4a4e-aa45-9a13013d925f.png">

- [ ] Token values component - #14274 
<img width="269" alt="Screen Shot 2022-03-30 at 1 22 21 PM" src="https://user-images.githubusercontent.com/43930900/160894541-f7fca935-d12d-433c-9aaa-2c5a06aee7b5.png">

- [ ] Token  component - #14169 
<img width="269" alt="Screen Shot 2022-03-18 at 4 34 02 PM" src="https://user-images.githubusercontent.com/43930900/159079455-f915f0bc-87b5-4232-a0d5-1140a380fc43.png">

- [ ] Parent component
<img width="278" alt="Screen Shot 2022-03-18 at 4 33 44 PM" src="https://user-images.githubusercontent.com/43930900/159079409-5d662f93-1469-4295-945e-0124245a735a.png">

- [ ] Ignore Token Modal
<img width="275" alt="Screen Shot 2022-03-18 at 4 35 14 PM" src="https://user-images.githubusercontent.com/43930900/159079594-212cb333-f565-45a9-91a8-4bf9e238ea52.png">

- [ ] Token added notification
<img width="217" alt="Screen Shot 2022-03-18 at 4 35 52 PM" src="https://user-images.githubusercontent.com/43930900/159079693-84be084d-5649-4484-8d1d-2ac79744e0df.png">
