### ISSUE TITLE
Remove 3box

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#14888]

**Comment by danjm** [comment]
- [ ] Add satisfactory replacement of the 3box feature
- [ ] Appropriate deprecation communications to users
- [ ] Merge https://github.com/MetaMask/metamask-extension/pull/14571

" Add satisfactory replacement of the 3box feature"

- MVP: a button for downloading the addressbook and preferences state and saving that to a json file, and add a button for uploading and restoring that state from such a file

"Appropriate deprecation communications to users"

- in app what's new notice to all 3box users
- notice should be 1 month before deprecation
- consult with design or product on wording of the notice
- support article, explain the deprecation and the new feature
- @danjm

**Comment by segun** [comment]
I am re-opening this PR because the solution will not work in MV3. There's no window.document in MV3, so when this [method](https://github.com/MetaMask/metamask-extension/blob/73bdbdde4fa89b6b767339b0ec8db16ea58ebb1c/shared/modules/export-utils.js#L3) is called from backup controller, it fails.

The solution that will work is for backup controller to send the data to be backed up to the UI and for the UI to call the above method.

**Comment by segun** [comment]
@danjm @hilvmason I think we can close this now.
