### ISSUE TITLE
MV3: Service Worker Compatibility with dApp

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#15984]
## Dependency Support
- Dapp Provider
- Dapp Legacy Provider
- Dapp Phishing Warning Page 

## UX Support

1. Dapp works on load.
2. If the service worker becomes inactive, the user can still interact with dapp which will restart the service worker.
3. If the extension is updated or installed during a dapp session, dapp should still work (verify this is supported in MV2 as well. If it's not, then maybe we don't need to support this). (https://github.com/metamask/metamask-extension/issues/15975)

## Specifications
- [x] Dapp should work on load whether accounts are connected or not
- [x] Dapp can send all types of transactions
- [x] At the start of a page session and when permitted accounts are connected, Service Worker is kept alive after being terminated.
- [x] At the start of a page session and when permitted accounts are not connected, the Service Worker stops running after being terminated. 
- [x] After a user connects an account to the dapp, the Service worker should be kept alive after being terminated.
- [x] After the Service Worker becomes inactive and the dapp attempts to use the provider, a message should be sent to the service worker to revive it. When the Service worker is revived, this should reestablish content scripts and stream connections.
- [ ] ~If a new version of the extension has been installed or updated during a dapp session, the dapp should continue to work. We should see `Error: Could not establish connection. Receiving end does not exist.` error, if dapp is not working.~ edit: no workarounds were found for this. We updated the error message to instruct user to restart.

## Backlog
- [ ] After a user disconnects an account to the dapp, the Service Worker should stop running after being terminated.
