### ISSUE TITLE
Mitigate Flaky Unit Tests

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16209]
**Context**: After including the metrics for Circle CI, we are now able to see the unit tests stats and identify most common intermitent failing tests.

https://app.circleci.com/insights/github/MetaMask/metamask-extension/workflows/test_and_release/tests?branch=develop

**What**: this epic will focus on mitigating the flaky unit tests.

- [ ] srp-input Show/hide SRP shown then hidden should prevent reading typed SRP
- [ ] srp-input Show/hide SRP shown after input should show words from typed SRP
- [ ] srp-input Show/hide SRP shown then hidden should prevent reading individually pasted SRP
- [ ] srp-input SRP validation error typed should show word requirement error if SRP has an unsupported word count above 12 but below 24
- [ ] GasDetailsItem should render label

![image.png](https://images.zenhubusercontent.com/621e5074355dc7130e44d3d0/4fcdf8ac-d47e-46f1-97a0-4be510f9736e)

**Comment by chloeYue** [comment]
Close this ticket because these unit tests are not flaky anymore
