### ISSUE TITLE
Security Meta Issue

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#163]
Using this issue to track improvements to our security protocol we'd like to adopt.
- [x] Publish source code publicly. #17
- [ ] Create mandatory review process in order to publish to Chrome store.
- [ ] Audit all dependencies
- [ ] Hard code all dependency versions.
- [ ] Check all dependencies into version control

**Comment by kumavis** [comment]
we should evaluate
https://github.com/organizations/metamask/settings/oauth_application_policy

**Comment by flyswatter** [comment]
There's a new API in town that may allow us to perform our injection with fewer permissions, narrowing the danger of a malicious metamask update. It is #813

**Comment by kumavis** [comment]
we have a date with cure53.de mid august (a couple weeks from now)

some other notes:
- [ ] add CSP
- [ ] look for `innerHTML` and `eval/Function` in deps

**Comment by kumavis** [comment]
this ticket was closed as our security audit recently completed
