### ISSUE TITLE
[Epic] Reduce E2E test flakiness

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17755]
### What is this about?

This is a placeholder epic for [Q1 O3KR3](https://docs.google.com/document/d/1EPPkQ6Mp-Xe2kKk1DULCi8aChqPf3MvmR5qk8n5DUoU/edit#bookmark=kix.j0wkj747c09p).

Context: In 2023, we created a dashboard in CircleCI that measures the number of flaky tests introduced by inaccurate and inconsistent tests.

Tactics:
- [ ] TBD

### Scenario

- NA

### Design

- NA

### Technical Details

- NA

### Threat Modeling Framework

- NA

### Acceptance Criteria

- NA

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [X] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

- NA

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by chloeYue** [comment]
Close this ticket because it's outdated
