### ISSUE TITLE
DS/Extension/2023/Q2/O1/KR3: ButtonIcon import clean up 

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#18493]
### Description
Continue `ButtonIcon` import clean up and migration of component to TS

### Tasks (separate PRs)
- [ ] Clean up imports and update JS to TS `ui/components/multichain`
- [ ] Clean up imports and update JS to TS `ui/components/institutional`
- [ ] Clean up imports and update JS to TS `ui/components/ui`
- [ ] Clean up imports and update JS to TS `ui/components/app`
- [ ] Clean up imports and update JS to TS `ui/pages`
- [ ] Clean up imports in all other folders
- [ ] Delete `component-name/deprecated` folder with JS components and consts

### Technical Details
- Update imports from  `'../../component-library/component-name/deprecated';` to `'../../component-library'`
- Update component instances from using JS consts to enums

### Acceptance Criteria 
- All components have been migrated to TS

**Comment by georgewrmarshall** [comment]
Last amount of clean up to go. Points should be reduced to reflect that.

<img width="298" alt="Screenshot 2023-05-18 at 11 36 48 AM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/0d350aad-8f25-482c-bdcc-f205eabd48e9">
