### ISSUE TITLE
DS/Extension/2023/Q2/O1/KR3: Icon import clean up 

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#18492]
### Description
Continue `Icon` import clean up and migration of component to TS

### Tasks (separate PRs)
- [x] Clean up imports and update JS to TS `ui/components/multichain`
- [x] Clean up imports and update JS to TS `ui/components/institutional`
- [x] Clean up imports and update JS to TS `ui/components/ui`
- [ ] Clean up imports and update JS to TS `ui/components/app`
- [ ] Clean up imports and update JS to TS `ui/pages`
- [ ] Clean up imports in all other folders
- [ ] Delete `component-name/deprecated` folder with JS components and consts

### Technical Details
- Update imports from  `'../../component-library/component-name/deprecated';` to `'../../component-library'`
- Update component instances from using JS consts to enums

### Acceptance Criteria 
- All components have been migrated to TS
