### ISSUE TITLE
Document e2e wiki

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#23499]
Framework of the e2e
- [ ] Document about introduction to automation
- [ ] Document about the Selenium automation tool
- [ ] Document about the programming language used
- [ ] Document about the CircleCI
- [ ] Provide details of the driver class we have in our e2e 

Setup
- [ ] Document about Fixtures
- [ ] Document about Ganache
- [ ] Document about Smart contract
- [ ] Document about mockTTP
- [ ] Document about RPC

Other 
- [ ] Update the ReadMe
- [ ] Upload document in the existing documentation
- [ ] Add JSDoc comments for certain functions.

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Document e2e wiki**
  - Given the e2e wiki is documented
  - When the documentation is reviewed
  - Then the documentation should cover the introduction to automation, Selenium automation tool, programming language used, CircleCI, driver class, fixtures, Ganache, smart contract, mockTTP, RPC, and be updated in the existing documentation
  - And JSDoc comments should be added for certain functions
- [ ] **Scenario: Update the ReadMe**
  - Given the ReadMe file is outdated
  - When it is updated to include the e2e wiki information
  - Then the ReadMe should accurately reflect the e2e wiki content and be up-to-date

**Comment by hjetpoluru** [comment]
Closing this ticket as the README has been completed.
