### ISSUE TITLE
Redesign Transaction Confirmations

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#23904]
## Designs

- [Confirmations Design System](https://www.figma.com/file/CeAIcptzeaI5ciTpYBaiqr/Confirmations-DS?type=design&node-id=37-6870&mode=design&t=w6NuX2gXIDb4UACy-0)
- [Transactions v4](https://www.figma.com/file/gcwF9smHsgvFWQK83lT5UU/Confirmation-redesign-V4?type=design&node-id=0-1&mode=design&t=1oagjn6UI3rxXtAx-0)
- [Transaction Simulations](https://www.figma.com/file/8DrinrQI4hs76Grm2F34xK/Simulations-MVP?type=design&node-id=0-1&mode=design&t=l9b1r6qOw7a8rBRw-0)
- [Alerts, Warnings, and Flags](https://www.figma.com/file/yUczlH2HbHaHsYijiONKx0/Warnings%2C-Alerts-and-Flags?type=design&node-id=0-1&mode=design&t=w6NuX2gXIDb4UACy-0)

## Affected Screens (User Stories)

- [ ] Contract Interaction #23905 
- [ ] Contract Deployment
- [ ] SIMPLE SEND (???)

### ERC20 Tokens

- [ ] Approve
- [ ] Increase Allowance
- [ ] Transfer
- [ ] Transfer From

### ERC721 Tokens

- [ ] Mint (not supported with a bespoke screen in legacy flows)
- [ ] Approve
- [ ] SetApprovalForAll: true
- [ ] SetApprovalForAll: false (Revoke)

### ERC1155 Tokens

- [ ] Mint Batch (not supported with a bespoke screen in legacy flows)
- [ ] Safe Batch Transfer From (not supported with a bespoke screen in legacy flows)
- [ ] SetApprovalForAll: true
- [ ] SetApprovalForAll: false (Revoke)
