### ISSUE TITLE
[EPIC] Migration from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28572]
### What is this about?

This ticket covers the effort required to migrate our continuous integration and deployment processes from CircleCI to GitHub Actions. The migration will involve:
- Evaluate the current CircleCI workflows and identify the equivalent configurations in GitHub Actions.
- Create and configure GitHub Actions workflows to replicate the existing CircleCI pipelines.
- Thoroughly test the new GitHub Actions workflows to ensure they function as expected and meet our CI/CD requirements.
- Gradually phase out CircleCI once the GitHub Actions workflows are fully operational and stable.

### Primary Outcomes

Bugs: Sometimes jobs need to be manually cancelled and retried due to a bug where jobs are stuck in an infinite loop. The logs show that all jobs are finished, but the machine remains running. Reference: https://consensys.slack.com/archives/C04KB2AUCD9/p1730131512414159. 

Ease of use: If we only used GitHub actions, it would be much easier to create charts and statistics, like it is required for https://github.com/MetaMask/MetaMask-planning/issues/3400. Now, when we want to create charts, we need to aggregate the results of workflows from two CI providers, which is rather painful.

Developer experience: 

1. CircleCI is not really developer friendly. They deprecated their V1 API, but did not migrate all the functionality of it. Some of the cool functions we would like to use are simply not present on V2. So now when you are developing, you need to use a mix of V1 and V2 apis to achieve what you want, including secret, undocumented, internal apis, which are hidden for outsiders, but are consumed internally by CircleCI.

2. There is no feature in CircleCI to ignore triggering CI when only the contents of a particular folder changed. Like, ignoring .github folder. We do not need to run all e2e tests because I changed the add-team-label workflow. https://consensys.slack.com/archives/C04KB2AUCD9/p1729018729923119. This feature would be nice for CI optimization.

3. CircleCI has no env variable that gives us the target branch for a PR. This a really fundamental feature missing (most requested feature https://ideas.circleci.com/config/p/provide-env-variable-for-branch-name-targeted-by-pull-request). We need to use hacky workarounds to run “get-changed-files-with-git-diff”, but this is supposed to be very simple.
4. This will significantly speed up CI by like some where around half which would significantly decrease merge time (increase contributor velocity). 

Cutting costs: GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners. CircleCI costs a lot, and the costs keep increasing as we add more and more workflows for automations. https://consensys.slack.com/archives/C04KB2AUCD9/p1731607601325019
- CircleCi - 100k per year specifically for Extension usage (might be more or less - but that order of magnitude)
On github actions we'd have to pay for self hosted runners for e2e tests (we can follow up with DevSecOps on runner type/costs, need a bit more investigation but we expect it to be low)

Runway related:
Runway needs to be provided a link to the build artifacts. If you provide it with CircleCi it can get it but we were thinking we could more easily use a github action for this purpose. It is easy to do on Github Actions now. In order to use Github Actions we would need to create a new job to upload the build to runway. This is independent of completing the transition away from CircleCi. [#29516](https://github.com/MetaMask/metamask-extension/issues/29516)

Alignment with Mobile: mobile also uses GitHub Actions instead of CircleCI. It will be easier to onboard developers, as they will only require knowledge of one CI provider. -- We need to investigate if we could move away from Bitrise in some ways which might save costs there? We should talk to @sethkfman about that. 

### Blockers
- Public artifact storage blocks us from completing any jobs which generate artifacts. (more than half of what is remaining, all builds ones)
  - solution discussed is to use s3 if we can get Jake's help on s3
- Flaky test tracking -- keeping the flaky test report working. It currently relys on CircleCi's test insights which Github actions has no equivalent for so we'd have to roll our own. This would block the e2e jobs migrations. 

### Estimated time
- If we can get help from DevSec help for s3 to remove the above blocker and dev focus of 1.5 devs full time we think around 2 ish weeks. 

### Refinement note:
- For most of the tasks the bulk of the work is understanding what the task is doing so fleshing out each of the subtasks is basically all the work for completing the subtasks so we won't do that in an ahead of time fashion. One big issue that has been encountered is that sometimes we hit tasks that are just not working at all and we have to figure out what to do in those cases. 

### Scenario

*Dependency Checks*
- [x] test-deps-audit
- [x] test-deps-depcheck
- [x] test-yarn-dedupe

*Linting*

- [x] test-lint-shellcheck
- [x] test-lint-changelog
- [x] test-lint-lockfile
- [x] test-lint

*Lava Moat*
- [x] validate-lavamoat-allow-scripts
- [x] validate-lavamoat-policy-build
- [x] validate-lavamoat-policy-webapp-beta
- [x] validate-lavamoat-policy-webapp-flask
- [x] validate-lavamoat-policy-webapp-main
- [x] validate-lavamoat-policy-webapp-mmi

*Beta Build*
- [x] trigger-beta-build
  - [x] validate-source-maps-beta
  
*Storybook*
- [x] prep-build-storybook
- [x] job-publish-storybook
- [x] test-storybook

*TypeScript Migration Dashboard*
- [x] prep-build-ts-migration-dashboard
  - [x] job-publish-ts-migration-dashboard
  
*Testing*
- [x] get-changed-files-with-git-diff

*Webpack*
- [x] prep-build-test-webpack
  - [x] test-e2e-chrome-webpack
  
*MV2*
- [x] prep-build-test-mv2
  - [x] test-e2e-firefox
  
*Flask MV2*
- [x] prep-build-test-flask-mv2
  - [x] test-e2e-firefox-flask
 
*Flask*
- [x] prep-build-test-flask
  - [x] test-e2e-chrome-flask
  
*General*
- [x] prep-build-test
  - [x] test-e2e-chrome
  - [x] test-e2e-chrome-multiple-providers
  - [x] test-e2e-chrome-rpc
  - [x] stats-module-load-init
  - [x] user-actions-benchmark
  - [x] benchmark
  
*MV2*
- [x] prep-build-mv2
  - [x] test-mozilla-lint-mv2
  - [x] validate-source-maps-mv2
  
*Flask MV2*
- [x] prep-build-flask-mv2
  - [x] validate-source-maps-flask-mv2
  - [x] test-mozilla-lint-flask-mv2
  
*General Build*
- [x] prep-build
  - [x] test-e2e-chrome-vault-decryption
  - [x] test-e2e-swap-playwright (OPTIONAL)
  - [x] validate-source-maps
  
_No response_

### Stakeholder review needed before the work gets merged

- [x] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [x] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by hjetpoluru** [comment]
Evaluate the current CircleCI workflows and identify the equivalent configurations in GitHub Actions.
- We currently have everything in the config.xml and environment variables in Circle CI settings.

**Comment by hjetpoluru** [comment]
We already have the [GitHub Actions workflow]( https://github.com/MetaMask/metamask-extension/blob/develop/.github/workflows/main.yml), need to translate the CircleCI concepts (executors, jobs, workflows, etc.) into their GitHub Actions equivalents. With help of gpt we should be able to convert this format conversion. 

Note - 
Cron : GitHub Actions does not support parallelism in the same way as CircleCI. You may need to split jobs manually if parallel execution is required or use the Selenium provided parallel execution.

**Comment by gauthierpetetin** [comment]
Notes from team refinement session:
- Github Actions also have a way parallelise as well, called "concurrency" and "matrix strategy"
- Number of workflows to migrate
- Advantages of moving to Github actions:
  - Github Actions are free on public Github repos, while circle.ci is not
- Consequences of moving to Github actions:
  - We'd need a new way to detect flaky tests, because that is currently done in circle.ci
  - We'll need to figure out where to store our env variables currently stored in circle.ci => Github secrets is a good place

**Comment by desi** [comment]
All subtasks have been moved to the Q2 Epic - #[31461](https://github.com/MetaMask/metamask-extension/issues/31461)
