### ISSUE TITLE
Create Feature to Suggest Users Try New UI Within the App

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3384]
We now have the beta UI bundled in MetaMask as published. The next step is to suggest users move over to the new UI, gently.

This is a ZenHub epic, and so issues added as dependencies of this epic will be considered blockers to rolling out this feature.

This feature should be kept on its own branch until those blockers are completed.

**Comment by danjm** [comment]
@cjeria @alextsg @danfinlay here is a list of style/design related dev tasks that I propose we prioritize for completion before as part of this epic (#3384). This is the list of 'minimum viable improvements/fixes' that I proposed at the design meeting on Thursday:

- [ ] Issues that have their own stand alone tickets: #3804, #4009, #4282, 
- [ ] Fix the overflow hiding the token name as see in #3478
- [ ] Data field parity with old UI by meeting requirements in this comment: https://github.com/MetaMask/metamask-extension/issues/3430#issuecomment-389962834

**Comment by danjm** [comment]
@cjeria @alextsg @danfinlay here is a list of style/design related dev tasks that I propose we prioritize for completion before as part of this epic (#3384). This is the list of 'minimum viable improvements/fixes' that I proposed at the design meeting on Thursday:

- [ ] Issues that have their own stand alone tickets: #3804, #4009, #4282, #3214, 
- [ ] Fix the overflow hiding the token name as see in #3478
- [ ] Data field parity with old UI by meeting requirements in this comment: https://github.com/MetaMask/metamask-extension/issues/3430#issuecomment-389962834
- [ ] Styling and copy changes to 'Reprice Transaction' screen shown in https://github.com/MetaMask/metamask-extension/issues/3885#issue-311441103
- [ ] Remove the From and To rows of the confirm screen to fix the scrolling issue mentioned in multiple tickets (e.g. eliminating scrolling is mentioned #4298, #3885) 
- [ ] Adding the account to the popup main screen as shown in comment https://github.com/MetaMask/metamask-extension/issues/3463#issuecomment-383676058
- [ ] Copy changes to confirm screen when handling ERC20 `approve` and `transferFrom` methods (@danfinlay I am suggesting we include this as a short term fix to a bigger issue. However, I'll note that we have never really come to consensus as to whether this should be done, and am happy to consider alternative approaches)
