### ISSUE TITLE
[DEV] - Enable and Document Development on Windows Native

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3426]
affects #3427

## Tasks

- [x] enable `METAMASK_ENV=test`
- [x] enable 'METAMASK_DEBUG=true'
- [x] enable mkdirp
- [x] ~enable or remove~ `[ $COVERALLS_REPO_TOKEN ]` - follow-up #3650

**Comment by lazaridiscom** [comment]
@Zanibas , note that a fresh installation on a supported system (windows 10) has test-problems, which is quite severe.

removing "METAMASK_ENV" in package.json works around the problem, then the next comes up:

```
if [ $COVERALLS_REPO_TOKEN ]; then nyc report --reporter=text-lcov | coveralls; fi
$COVERALLS_REPO_TOKEN was unexpected at this time.
```

Possibly windows support was not tested yet on from-scratch dev-environments.

**Comment by lazaridiscom** [comment]
Unit tests work fine, with "METAMASK_ENV=test" removed in package.json
`    "test:unit": "mocha --exit --require babel-core/register --require test/helper.js --recursive \"test/unit/**/*.js\""`

**Comment by lazaridiscom** [comment]
Closed by accident. @danfinlay , can you please reopen?

**Comment by lazaridiscom** [comment]
@kumavis , this line fails under windows. Could you remove the "if" block, or move this over to a gulp task?

```
    "test:coveralls-upload": "if [ $COVERALLS_REPO_TOKEN ]; then nyc report --reporter=text-lcov | coveralls; fi",
```

**Comment by lazaridiscom** [comment]
follow-up: #3650
