### ISSUE TITLE
[TASK] MetaMask Multi-Keyring (Phase One)

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3427]
# MetaMask Multi-Keyring

(Based on #3249, stripped down to a realistic 1st Phase)

MetaMask only accepts two types of signers (both key pairs), the 12-word mnemonic, and the imported private key.

## The Keyring Class

https://github.com/MetaMask/eth-simple-keyring#the-keyring-class-protocol

* Keyring Class is a JavaScript protocol that objects can adhere to, and be added to MetaMask as new signing strategies.
* Currently Missing: custom signing views

## Phase One

Update: 2018-03-18

- [x] Ensure that the basic-signer is based on the Keyring Class
- [x] Ensure a "Signer Array", which holds all the singers (at this point only basic-signer). This either exists, or provide.
- [x]  implement  a second signer based on KeyringClass (can be very simple, but fully functional)
- [x] Signer Array holds now 2 different signers.
- [x] Place In-Code instructions 82ae138 
- [x] ~The new signers can have Wreck UI (no design, e.g. pure html)~
- [x] ~Provide a PoC that this actually works (Quick&Dirty, can be even with browser-console commands)~
- [x] cleanup, move open issues over to #3631, close

2018-03-20 - Code has already 2 different signers. Together with a dummySigner, those become 3.

## Estimated Duration

**14 to 28 days** (in parallel with teach-in, code-refactoring and smaller project-organization steps, mainly within the related code-subsystems)

## ~~Bounty~~ Task Details

"On your own risk" removed.

## Further Phases

2018-03-20

* Phase two (Core & UI): #3631
* Phase three (Code & Project)

## Important to Realize

A Multi-Signer Implementation without a smooth running MM project (= reorganized project) can lead to a support-disaster (amount of incidents far above processing capacity).

## Even More Important
2018-03-06 

The above (the plan) is already a work-result (as I was breeding about this since around two weeks - not full-time of course, more in background). One of the most important parts of this overall task is to add this functionality "chirurgical" (as in "without breaking the underlying code").

So, ideally, the implementation would be done by:

* Non-Breaking Code-Additions
* Non-Breaking Refactoring

Good news: those are my strong points.

(as a sidenote: my weak points are "solving problems which need much code-volume". I collapse, as I naturally try to shrink code-size)

**Comment by lazaridiscom** [comment]
Unexpected Surprise: till now, the relevant code is cleanly written and good documented!

@danfinlay , I just need a "go" from you, and we can workout the other formalities later. (You have possibly noticed the "~~Bounty~~ Task" thingy, which is just a hint to my wishes, not requirements.)

**Comment by lazaridiscom** [comment]
## Even More Important

The above (the plan) is already a work-result (as I was breeding about this since around two weeks - not full-time of course, more in background). One of the most important parts of this overall task is to add this functionality "chirurgical" (as in "without breaking the underlying code").

So, ideally, the implementation would be done by:

* Non-Breaking Code-Additions
* Non-Breaking Refactoring

Good news: those are my strong points.

(as a sidenote: my weak points are "solving problems which need much code-volume". I collapse, as I naturally try to shrink code-size)

**Comment by lazaridiscom** [comment]
follow-up: #3631
