### ISSUE TITLE
[TASK] MetaMask Multi-X (Phase Two)

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3631]
**! Work Issue: Permanently Revised !**

continuation of #3427
<hr/>

(draft)

This phase introduces changes that go beyond refactoring.

It can be applied to the current source-code as-is (2 keyring-classes), without the need to introduce any new keyring classes.

## Steps

(Note: the hierarchy indicates necessary sub-tasks. Those were either directly visible, or they came up during ongoing work. Example: #3757 => A Redesign became necessary).

- [x] #3666 - Provide Generic AccountNew Menu
- [x] #3568 - Rework "metamask-controller.js" (partially)
- [x] #3757 - Redesign mm-vault (partially)
- [x] Add 3rd dummy-Keyring to extract generic UI requirements
- [x] Cleanup, Move Open Issues over to #3679 and #3757, Close

## Estimated Duration

14 to 28 days

Clarification: this would mean: Ledger Support (if all goes fine). If not, then the 3rd phase must be done first.

## What happened?

* Attempted Refactoring  => not possible to achieve goals
* Attempted Rework (introduces changes, but overall architecture remains) => not possible to achieve goals
* Finally started a Redesign (will introduce overall architectural changes), trying to keep as much as possible backwards-compatible.

See #3757 

## Further Phases

* #3679 Phase three (Code & Project)

**Comment by lazaridiscom** [comment]
Closing, follow-up: #3679 & #3757

**Comment by lazaridiscom** [comment]
follow-up: #4060
