### ISSUE TITLE
Clean up network config

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3653]
Currently our [network config file](https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/config.js) is not very representative of the app:

- [ ] The Beta UI does not use its own network config.
- [ ] We no longer use any of these URLs for Infura connection.
- [ ] We no longer use this DEFAULT_RPC value (So where do we GET our default RPC?)
- [x] `networkController.initializeProvider` appears to be dead code.

Discovered this problem while trying to answer https://github.com/MetaMask/metamask-extension/issues/3647

**Comment by alextsg** [comment]
@danfinlay Creating a PR to clean up the network config by creating a `network` folder for the `NetworkController` and moving enums there, along with adding a util file for utility functions related to the network.

Addressing each line of the checklist:
* The Beta UI does not use its own network config.
* We no longer use any of these URLs for Infura connection.

These URLs are still getting passed into `_configureInfuraProvider`, where `getRpcAddressForType` is returning the URL based on the network. I don't think we can remove these yet.

* We no longer use this DEFAULT_RPC value (So where do we GET our default RPC?)

Changing `app/scripts/first-time-state.js` to import the default network from the enums file so that the file can be used as a source of truth.

* networkController.initializeProvider appears to be dead code.

It looks like `metamask-controller.js` is calling `initializeProvider` here: https://github.com/MetaMask/metamask-extension/blob/29dab1e9e00c1c1e6ad834026df51b2839d3171d/app/scripts/metamask-controller.js#L269
