### ISSUE TITLE
4.x versions of MetaMask missing from addons.mozilla.org

### ISSUE THREAD

**Issue by rossng** [MetaMask/metamask-extension#4118]
All 4.x versions of MetaMask seem to have disappeared from AMO. The latest release is from January 29.

[Full list of versions](https://addons.mozilla.org/en-GB/firefox/addon/ether-metamask/versions/).

**Comment by frankiebee** [comment]
We were having issues with publishing to firefox ( captured here #3999 ) which has just been fixed so hopefully we can get the new version to you soon.

**Comment by filips123** [comment]
When will be this fixed?

**Comment by abitrolly** [comment]
* [ ] #3999 - deterministic builds for Firefox
  * [ ] https://github.com/browserify/browserify/issues/1796 - deterministic browserify
    * [x] https://github.com/hughsk/uglifyify/issues/61#issuecomment-292025091 - deterministic uglifyify (fixed in https://github.com/hughsk/uglifyify/pull/62)
    * [ ] https://github.com/MetaMask/metamask-extension/issues/4098 - use fixed uglifyify from npm
      * [x] uglifyify is removed https://github.com/MetaMask/metamask-extension/pull/4111
* [ ] https://github.com/MetaMask/metamask-extension/issues/3664 - deterministic bundle script

**Comment by bastiaanb** [comment]
maybe related: a 4.6.1 release for FF is available on GitHub, but uninstallable on FF >= 57, because it the add-on has not been signed. https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by michael1011** [comment]
A hacky workaround for @bastiaanb signing issue:
- go to `about:config`
- set `xpinstall.signatures.required` to false

**Comment by filips123** [comment]
@michael1011 This only works in Firefox ESR, Firefox Developer Edition and Nightly.

> **What are my options if I want to use an unsigned add-on? (advanced users)**
> 
> Firefox Extended Support Release (ESR), Firefox Developer Edition and Nightly versions of Firefox will allow you to override the setting to enforce the add-on signing requirement by changing the preference xpinstall.signatures.required to false in the Firefox Configuration Editor (about:config page). There are also special unbranded versions of Firefox that allow this override. See the MozillaWiki article, Add-ons/Extension Signing for more information.

**Comment by bastiaanb** [comment]
@michael1011, @filips123 thanks for the info! The Firefox version in Fedora, also allows overriding, apparently.

**Comment by aelam** [comment]
How about signing the firefox extension to make the signatures corrected,
then we don't need to set `xpinstall.signatures.required` to `false`

**Comment by kumavis** [comment]
published
