### ISSUE TITLE
Re-organize and break out pieces of metamask reducer

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6231]
# Description
The metamask reducer is over bloated with states that could be re-organized into reducers/sub-reducers. This over bloated state lowers discoverability and maintainability of the codebase.

# Problems

### 1. The following states are inside metamask, but it should be in appState
```
isAccountMenuOpen: false
isInitialized: true
isMascara: false
isPopup: false
isRevealingSeedWords: false
isUnlocked: true
```

### 2. The following states are inside metamask, but it should be separated into a preference reducer
```
preferences: {...}
useBlockie: true
settings: {ticker: "ETH"}
featureFlags: {privacyMode: true, sendHexData: true}
```

### 3. The following states can be separated into a pendingTransactions reducer
```
unapprovedMsgCount: 0
unapprovedMsgs: {}
unapprovedPersonalMsgCount: 0
unapprovedPersonalMsgs: {}
unapprovedTxs: {}
unapprovedTypedMessages: {}
unapprovedTypedMessagesCount: 0
```

# Proposed New States
```
- pendingTransactions (any states that relates to unapproved msgs)
- accounts (any states that relates to users' account/identities)
- network (any states that has to do with infura/recent blocks status)
- preferences (any states that has to do with user preferences)
```

The end result should remove `metamask` reducer completely (since it does not describe the nature of the state), and re-organize into new/existing reducers.

# Tasks
- [ ] JC/DM/WW to propose and finalize shape of new redux state
- [ ] Start with moving states into existing reducers, update JSDoc
- [ ] Follow with moving states into new reducers, update JSDoc
- [ ] [STRETCH] Add typescript definition to all reducers state

Note: the above was prepared by @chikeichan

**Comment by brad-decker** [comment]
@danjm this is stale, i'm going to close as we start to solidify plans around state as part of #17255
