### ISSUE TITLE
multiple providers: work tracker issue

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#6902]
goal:
initialize all providers instead of creating and destroying on network switch while maintaining same external behavior

high level todos:
  - [x] (Migration needed) pass in all end points
  - [X] remove the storage of endpoints from preferences controller
  - [x] initialize all providers
  - [x] continue same external behavior of the provider 
  - [ ] QA
  - [ ] some UI tweaks for sanity of params
  - [ ] frankie dont go to overboard

**Comment by frankiebee** [comment]
current status: broke up provider initialization and proxy management into to files

notes/low level todos:
  default networks:
  - [ ] never initialize any local hosts
  - [ ] if selected network  is a non infura fallback to infura if possible

**Comment by frankiebee** [comment]
MIGRATION NEEDS:
PreferencesController.frequentRpcListDetail -> NetworkController.networkConfigs

**Comment by frankiebee** [comment]
O_O clean up network preferences...

**Comment by frankiebee** [comment]
if possible unify object in network controller:
  rpcTarget -> rpcUrl
  networkConfig = {
    rpcUrl,
    type, // default#type(chainId) || custom#type(chainId) ???
    name,
    chainId,
    blockExplorer,
  }

  network class config:

  config: {
    rpcUrl,
    type,
    chainId, // for ethClassic
  }

**Comment by frankiebee** [comment]
- [ ] ui needs some method updates

**Comment by frankiebee** [comment]
updateAndSetCustomRpc -> takes a single object 
`  async updateAndSetCustomRpc (networkConfig) {`

**Comment by frankiebee** [comment]
actual: 

```js
networkConfig = {
    rpcUrl,
    type, // default#type(chainId) || custom#type(chainId) ???
    custom: {
      name,
      chainId,
      blockExplorer,
      ticker,
    }
  }
```

**Comment by frankiebee** [comment]
- [ ] ensure the initialize param is discarded if passed to the constructor

**Comment by frankiebee** [comment]
wooooooooooo 
```
  1104 passing (5s)
  2 failing
```
sooooo close and yet so far

**Comment by danfinlay** [comment]
Let's take a little time to explore H4v0c's work on abstracting multiple chain providers, see if there's a chance to leverage their work at all: http://chainstackjs.org/

**Comment by frankiebee** [comment]
- [ ] needs docs
