### ISSUE TITLE
Replace usages of inherits with ES6 classes

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/metamask-extension#7766]
Files with [`inherits`](https://nodejs.org/api/util.html#util_util_inherits_constructor_superconstructor) usages:

- [x] `ui/app/components/app/account-panel.js` (#7775)
- [x] `ui/app/components/app/customize-gas-modal/gas-modal-card.js` (#7776)
- [x] `ui/app/components/app/customize-gas-modal/index.js` (#7776)
- [x] `ui/app/components/app/dropdowns/account-details-dropdown.js` (#7777)
- [x] `ui/app/components/app/dropdowns/network-dropdown.js` (#7778)
- [x] `ui/app/components/app/dropdowns/token-menu-dropdown.js` (#7779)
- [x] `ui/app/components/app/input-number.js` (#7780)
- [x] `ui/app/components/app/menu-droppo.js` (#7781)
- [x] `ui/app/components/app/modals/hide-token-confirmation-modal.js` (#7782)
- [x] `ui/app/components/app/modals/modal.js` (#7783)
- [x] `ui/app/components/app/network.js` (#7784)
- [x] `ui/app/components/app/token-list.js` (#7785)
- [x] `ui/app/components/ui/fiat-value.js` (#7786)
- [x] `ui/app/components/ui/mascot.js` (#7787)
- [x] `ui/app/components/ui/readonly-input.js` (#7788)
- [x] `ui/app/pages/confirm-transaction/conf-tx.js` (#7790)
- [x] `ui/app/pages/create-account/import-account/index.js` (#7791)
- [x] `ui/app/pages/create-account/import-account/private-key.js` (#7791)
- [x] `ui/lib/persistent-form.js` (#7770)
