### ISSUE TITLE
Remaining work for LoginPerSite

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#8248]
This issue represents the remaining work for LPS.

Account Switching Behaviour:

- [x]  Move Assets list to home page, removing the sidebar (@Gudahtt, #8264)
    - The new status icon is in the same screen real estate as the old hamburger menu for the sidebar. The only unique information available in this sidebar is the token list; everything else is available already on the home screen (e.g. the address, avatar, and name of the current account) or in the Account Options menu (e.g. the Account Details modal). So this sidebar menu is to be removed, and the "Assets" tab added to the home screen in its place.
    - This only applies to the small-screen UI (e.g. the popup, or fullscreen in a popup-sized window). 
    - ~The fullscreen UI would be removed, and replaced by the new fullscreen UI design that is more similar to the new popup design. ([Figma](https://www.figma.com/file/b8U583mpXW1FsPWfGFNT8C/Wallet-home-(full-screen)?node-id=8%3A1))~ This has been postponed, and will be done separately later.
- [x]  Re-style the connected sites modal to match the Figma design (@whymarrh, #8262)
- [x] Factor out popover changes from connected sites modal (@whymarrh, #8253)
- [x]  Add the connected status indicator to the home page of the popup UI (@danjm, [Figma](https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-%2F-Login-Per-Site?node-id=955%3A107), #8270)
    - This indicator should be green if the site in the active tab is connected to the current account, yellow if the site is connected to a different account, grey if it's connected to no accounts.
    - It should be omitted in the fullscreen or notification home screen UI
- [x] Build the connected accounts modal ([Figma](https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-%2F-Login-Per-Site?node-id=1988%3A337), @whymarrh)
- [x]  When the status indicator is green, clicking it brings you to the "Connected accounts" modal for the current site (@whymarrh)
- [x]  When the status indicator is yellow, clicking it brings you to the "Connected accounts" modal, with the current account highlighted in yellow at the top and styled differently (see Figma, @whymarrh)
- [x]  When the status indicator is grey, clicking it brings you to the message advising the user to connect via the dapp (@whymarrh)
- [x]  Add options menu to each account on the Connected Accounts modal (@whymarrh)
- [x]  Add pop-up for existing users to explain this new feature, highlighting the status indicator (@danjm, [Figma](https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-%2F-Login-Per-Site?node-id=952%3A512))
- [x]  Alert the user when switching from an account connected to the active tab to an unconnected account ([Figma](https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-%2F-Login-Per-Site?node-id=1929%3A139)) (@Gudahtt)
- [x] Alert the user upon opening the popup when the current account is not connected to the active tab, but some other account is ([Figma](https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-%2F-Login-Per-Site?node-id=1940%3A192)) (@Gudahtt)

Connect flow:

~~- [ ] Adds styled boxes for notifications, and associated storybook stories (#8071, @danjm)~~
- [x] Allow selecting multiple accounts in Connect flow (#8078, @danjm)
- [x] Add multi accounts tooltip to connect flow (#8181, @danjm)
- [x] Redesign for pop up view ([Figma](https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-%2F-Login-Per-Site?node-id=378%3A4527), @danjm)

Other:
- [x] Fix use of webpack loaders in components (@Gudahtt)
- [x] Fix token list when token balances are zero (@Gudahtt)
- [x] fix `signTypedData_v4` bug on develop (@rekmarks, #8265)

~- [ ] Use Font Awesome pro (@Gudahtt)~

**Comment by Gudahtt** [comment]
This has been completed
