### ISSUE TITLE
here some potential milestones:

### ISSUE THREAD

**Issue by miranda76** [MetaMask/metamask-extension#9912]
here some potential milestones:
- [ ] invite only beta
  - [ ] first time flow
  - [ ] account CRUD
  - [ ] per-domain config
  - [ ] testnet/mainnet
  - [ ] select RPC
- [ ] public beta
  - [ ] updated home page
  - [ ] chrome store screenshots + copy
  - [ ] list of dapps that work
  - [ ] software licenses
  - [ ] resolve backend issues (method whitelist)
- [ ] public launch
  - [ ] spiffy home page
  - [ ] email blast, consensys email, blog, hacker news, etc
  - [ ] dapp store integration
- [ ] second wave
  - [ ] reactive blockchain store lib
  - [ ] zero-client lib (user doesnt need any integration)
  - [ ] light-client friendly dapp tutorial
  - [ ] firefox support

_Originally posted by @kumavis in https://github.com/MetaMask/metamask-extension/issues/4#issuecomment-183973105_

**Comment by tmashuang** [comment]
Please don't spam issues like this.
